### ISSUE TITLE
still or again: list buttons are vanishing on hover

### ISSUE THREAD

**Issue by trob** [Fabrik/bootstrap3-jlayouts#10]
because "somebody" is adding class .open on hover
and purity_iii has
.open {background: transparent,color:white}
which will be invisible on a white content background

**Comment by trob** [comment]
adding

```
.fabrikButtonsContainer .nav .open {background:#eeeeee;}
.fabrikButtonsContainer .nav .open >a:hover,.fabrikButtonsContainer .nav .open >a{background:#eeeeee;color:black;}
```

to where? would fix it.

**Comment by pollen8** [comment]
hi - I'm not seeing the same bug
For me the hover works ok, however the trigger button is hidden when you close the list dropdown.
This commit should fix that 
https://github.com/Fabrik/fabrik/commit/a89e8f9bdb56899e786a28dddfaeaaad5e028feb
could you confirm that the hover thing is still an issue?
thanks

**Comment by pollen8** [comment]
ah OK top list buttons like 'add' etc - yes I see the css issue now

**Comment by pollen8** [comment]
this seems an issue specifically with t3 or the purity III template. the 'fix' they propse is to add the following css to your template custom css section:
(https://www.joomlart.com/forums/topic/i-looking-for-a-static-side-menu/page/3/)

```
.nav .open > a,
.nav .open > a:hover,
.nav .open > a:focus {
background: #eee;
color: #000;
}
```

This is not our responsibility to add to our code so I am closing this ticket

**Comment by trob** [comment]
"This is not our responsibility..."
Principially, yes.
But you are using Purity_III as reference to demonstrate that Fabrik is working with BS3, too.
So it should be at least in the Readme (and maybe a WIKI section).
