### ISSUE TITLE
old T3 issue: Title of article is gone

### ISSUE THREAD

**Issue by trob** [Fabrik/bootstrap3-jlayouts#11]
Article with Fabrik content is missing it's title.
Solution:
http://fabrikar.com/forums/index.php?threads/purity-iii-template-article-title-issue.41844/#post-212765

It's not "layouts" but maybe the patch/override file can be included here, too.

**Comment by pollen8** [comment]
Its a Joomla content layout - I don't think that's our responsibility to include?
it would be better to inform T3 of this and get them to fix
