### ISSUE TITLE
element error messages

### ISSUE THREAD

**Issue by trob** [Fabrik/bootstrap3-jlayouts#13]
non-ajax validation (= error message below element after Save):

Protostar is doing
.control-group.error .control-label, .control-group.error .help-block, .control-group.error .help-inline {
    color: #b94a48;
}

this is missing in Purity_III, so it's just the text, nothing red...

fa-exclamation-sign doesn't exist (ok, icon-exclamation-sign isnot longer defined, too)
should be warning (fa-warning, icon-warning)
ok, seems this has changed; the new default in fabrik.xml is "warning" but this won't change any setting in existing installaions until it's changed manually in Fabrik Options.

Eclamation-sign is still hardcoded in
\components\com_fabrik\models\element.php (1 hits)
    Line 1691:          $icon        = FabrikWorker::j3() ? $usersConfig->get('error_icon', 'exclamation-sign') . '.png' : 'alert.png';
\components\com_fabrik\views\form\view.base.php (1 hits)
    Line 759:       $errorIcon       = FabrikWorker::j3() ? $fbConfig->get('error_icon', 'exclamation-sign') . '.png' : 'alert.png';
(but I assume those defaults will never be applied).

**Comment by pollen8** [comment]
![image](https://cloud.githubusercontent.com/assets/28268/12914436/96f95ba2-cf24-11e5-9f88-17b812bc01f9.png)

I've moved the error into its own jlayout and I think i've added the correct classes to the control-group div. I don't see an issue with the icon (see screen shot)

**Comment by trob** [comment]
Icon is depending on 

>  ok, seems this has changed; the new default in fabrik.xml is "warning" but this won't change any setting in existing installaions until it's changed manually in Fabrik Options.

So the user must set it in Fabrik options.

But from where do you get the red color?

> I've moved the error into its own jlayout
> I can't see one, did you push?

**Comment by trob** [comment]
yup, ok now

**Comment by pollen8** [comment]
It's in the main fabrik repo. No need for an override. The text class ro
make the text red has also been added in the main repo
