### ISSUE TITLE
Bootstrap 3 alt layout isn't selectable

### ISSUE THREAD

**Issue by N6REJ** [Fabrik/bootstrap3-jlayouts#17]
I'm using Fabrik 3.4.3 and I downloaded and put in place the bootstrap 3 layout.
![image](https://cloud.githubusercontent.com/assets/1850089/15104293/0efce5fe-157c-11e6-9dbe-bb2e098b5306.png)

But its not showing up in the admin of the form.
![image](https://cloud.githubusercontent.com/assets/1850089/15104308/46f0d66e-157c-11e6-9309-934735a39d57.png)

Is there something I'm doing wrong?

**Comment by pollen8** [comment]
JLayouts are not Fabrik list/details/form templates, so wont show up there.
Instead they alter markup on a smaller level. So for example the markup to create a progress bar is not the same in bootstrap 2 as it is in bootstrap 3.
Each layout file attempts to address rendering issues at this level, so a Fabrik form template may make use of several different JLayouts whilst rendering itself but its not something you can choose in the Fabrik UI

**Comment by N6REJ** [comment]
oh ok, so I need to take the bootstrap template, convert it and then the layout will react as needed...
ty.
