### ISSUE TITLE
JS error with spinner

### ISSUE THREAD

**Issue by trob** [Fabrik/bootstrap3-jlayouts#2]
With purity_iii in every form I see a JS error like
GET http://localhost/j33/index.php/%3Cspan%20class=%22fa%20fa-spinner%20fa-spin%22%20%3E%3C/span%3E 404 (Kategorie nicht gefunden)
span%3E:1 

or
GET http://localhost/j33/index.php/strassen-list/form/51/%3Cspan%20class=%22fa%20fa-spinner%20fa-spin%22%20%3E%3C/span%3E 500 (View nicht gefunden [Name, Typ, PrÃ¤fix]: form, span, fabrikView)
span%3E:1 

It seems it is not related to an element type (forms are without calc or CDD)

**Comment by cheesegrits** [comment]
Yeah, I see this too. Working on it.

**Comment by cheesegrits** [comment]
https://github.com/Fabrik/fabrik/commit/652f2050585fe87ee30c1fd5e1ae9ee2febd2324
