### ISSUE TITLE
input-append

### ISSUE THREAD

**Issue by trob** [Fabrik/bootstrap3-jlayouts#4]
protostar is doing a general
input[type="xyz"] display:inline-block;

purity_iii is doing
input[type="xyz"] display:block;

something like
.input-append input... {display:inline-block;}
is missing in both templates, in protostar it doesn't matter but in purity_iii the calendar icon is displayed below the date input field.

see http://fabrikar.com/forums/index.php?threads/bootstrap3-jlayouts-calenadar-icon.42430/

**Comment by cheesegrits** [comment]
Should be fixed in https://github.com/Fabrik/bootstrap3-jlayouts/commit/b2da078ed4a1ac0a5811fe9d75591ea23a06711a
